version: '3.5'
services:
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - catalog
    - matteo_sensor1
    - pippo_sensor1
  catalog:
    build: ./catalog
    image: catalog
    expose:
    - '80'
    ports:
    - 8080:80
  matteo_sensor1:
    build: ./sensor
    container_name: matteo_sensor1
    image: sensor1
    expose:
    - '80'
    environment:
      userID: matteo
      deviceID: sensor1
    ports:
    - 8082:80
    links:
    - catalog
    depends_on:
    - catalog
  pippo_sensor1:
    build: ./sensor
    container_name: pippo_sensor1
    image: sensor1
    expose:
    - '80'
    environment:
      userID: pippo
      deviceID: sensor1
    ports:
    - 8084:80
    links:
    - catalog
    depends_on:
    - catalog
