version: '3.5'
services:
  nginx:
    image: nginx:latest
    ports:
    - 80:80
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - catalog
    - sensor1
  catalog:
    build: ./catalog
    image: catalog
    expose:
    - '80'
    ports:
    - 8080:80
  sensor1:
    build: ./sensor
    container_name: matteo_sensor1
    image: sensor1
    expose:
    - '80'
    ports:
    - 8082:80
    links:
    - catalog
    depends_on:
    - catalog
