version: '3.5'
services:
    catalog:
      build: ./catalog
      expose:
        - "80"
      ports: 
        - "8080:80"
    sensor:
      build: ./sensor
      expose:
        - "80"
      ports: 
        - "9080-9090:80"
      depends_on: 
        - catalog    
      links:
        - catalog
