version: '3'
services:
    catalog:
      build: ./catalog
      expose:
        - "80"
      ports: 
        - "8080:80"
    sensor:
      build: ./sensor
      expose:
        - "80"
      ports: 
        - "9080-9090:80"    
      links:
        - catalog
